// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/kids1934/gomall/app/frontend/biz/router/about"
	"github.com/kids1934/gomall/app/frontend/biz/router/auth"
	"github.com/kids1934/gomall/app/frontend/biz/router/cart"
	"github.com/kids1934/gomall/app/frontend/biz/router/category"
	"github.com/kids1934/gomall/app/frontend/biz/router/checkout"
	"github.com/kids1934/gomall/app/frontend/biz/router/home"
	"github.com/kids1934/gomall/app/frontend/biz/router/order"
	"github.com/kids1934/gomall/app/frontend/biz/router/product"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	about.Register(r)

	order.Register(r)

	checkout.Register(r)

	auth.Register(r)

	cart.Register(r)

	category.Register(r)

	product.Register(r)

	home.Register(r)
}
